spring.application.name=notification-system
# Kafka Configuration (local setup)
spring.kafka.bootstrap-service=localhost:9092

# Disable Kafka auto-start (important)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.missing-topics-fatal=false

# Consumer group ID
spring.kafka.consumer.group-id=notification-group

# Deserialize JSON automatically
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust all packages (for now, dev only)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Serialize JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#-->What This Config Does
#--Connects your app to Kafka running locally
#--Converts Java objects ? JSON (producer)
#--Converts JSON ? Java objects (consumer)
#? Without this ? Kafka won?t work properly.